### ISSUE TITLE
Ejercicio21

### ISSUE THREAD

**Issue by antu221** [glantucan/math_exercises#4]
He intentado haciendo que al llegar a la posición indicada la velocidad se reduzca a 0 mediante estas lineas:

``` C#
if (player.transform.position == controlPoint)
v = 0f;
```

Pero dado que para que coincidan exactamente en la misma posicion hay que tener una suerte mayor que la del euromillones, estas lineas no sirven.

He buscado en la ayuda de Unity y he encontrado `Vector3.MoveTowards` pero no parece ser exactamente lo que necesito.

**Comment by glantucan** [comment]
Como os expliqué, este no es el foro, debéis preguntar **todas** las preguntas, sean de lo que sean, en el de el repositorio [puzzle_game](https://github.com/glantucan/puzzle_game/issues), para que esté todo junto, que si no es un caos.
He creado allí un hilo para tu pregunta:
https://github.com/glantucan/puzzle_game/issues/5#issuecomment-256088269
